dist: bionic
language: php

env:
  global:
    - SETUP=stable

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo apt-get update
  - sudo apt-get install poppler-utils
  - sudo apt-get -y install libvips libvips-dev libvips-tools
  - vips -v
  - phpenv config-rm xdebug.ini || true
  - printf "\n" | pecl install -f pecl install vips
  - echo "extension = vips.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install:
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: vendor/bin/phpunit
